function pktLog = initPacketLog(maxRows)

    empty = struct( ...
        'packetId', 0, ...
        'nodeId', 0, ...
        'type', 0, ...
        'genTime', 0, ...
        'deadlineTime', inf, ...
        'success', 0, ...
        'successTime', NaN, ...
        'delay', NaN, ...
        'deadlineMet', 0, ...
        'attempts', 0, ...
        'failureReason', "");

    pktLog = repmat(empty, maxRows, 1);
end