function txLog = initTxLog(maxRows)

    empty = struct( ...
        'packetId', 0, ...
        'nodeId', 0, ...
        'slot', 0, ...
        'channel', 0, ...
        'branch', 0, ...
        'packetType', 0, ...
        'powerClass', "", ...
        'Pr_dBm', NaN, ...
        'success', 0, ...
        'collision', 0);

    txLog = repmat(empty, maxRows, 1);
end